apiVersion: v1
kind: Pod
metadata:
  name: demo-invalid-pod
  namespace: policy
  annotations:
    smaitic.com/inject-secrets-poc: "demo-invalid-pod"
spec:
  containers:
    - name: app
      image: busybox:latest
