environments:
  minikube: {}
---
releases:
  - name: kyverno-policies
    chart: ./helm-charts/kyverno-policies

  - name: workloads
    namespace: policy
    chart: ./helm-charts/workloads
    values:
      - ./override.yaml
