apiVersion: v1
kind: Pod
metadata:
  name: demo-01-basic-injection
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ .Values.annotationKey }}: "demo-01-basic-injection"
spec:
  containers:
    - name: app
      image: {{ .Values.app.image }}
      command: ["sleep", "3600"]
