apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-app
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ .Values.annotationKey }}: "poc-app"
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: poc-app
  template:
    metadata:
      labels:
        app: poc-app
      annotations:
        {{ .Values.annotationKey }}: "poc-app"
    spec:
      containers:
        - name: poc-app
          image: busybox:1.37
          command: ["sleep", "3600"]
