apiVersion: batch/v1
kind: CronJob
metadata:
  name: poc-cronjob-5min
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ .Values.annotationKey }}: "poc-cronjob-5min"
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            {{ .Values.annotationKey }}: "poc-cronjob-5min"
        spec:
          restartPolicy: Never
          containers:
            - name: cron-worker
              image: {{ .Values.app.image }}
              command: ["sleep", "5"]
