apiVersion: v1
kind: Pod
metadata:
  name: demo-04-backend-probes
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ .Values.annotationKey }}: "demo-04-backend-probes"
    smaitic.com/kyverno/health-config: "bridge"
spec:
  containers:
    - name: app
      image: {{ .Values.app.image }}
      command: ["sleep", "3600"]
      ports:
        - containerPort: 9988
