apiVersion: v1
kind: Pod
metadata:
  name: demo-05-frontend-probes
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ .Values.annotationKey }}: "demo-05-frontend-probes"
    smaitic.com/health-config: "frontend"
spec:
  containers:
    - name: app
      image: {{ .Values.app.image }}
      command: ["sleep", "3600"]
      ports:
        - containerPort: 8080
