apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-1min
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ .Values.annotationKey }}: "cronjob-1min"
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            {{ .Values.annotationKey }}: "cronjob-1min"
        spec:
          restartPolicy: Never
          containers:
            - name: cron-worker
              image: {{ .Values.app.image }}
              command: ["sleep", "5"]
