apiVersion: apps/v1
kind: Deployment
metadata:
  name: full-injection
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ .Values.annotationKey }}: "full-injection"
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: full-injection
  template:
    metadata:
      labels:
        app: full-injection
      annotations:
        {{ .Values.annotationKey }}: "full-injection"
        smaitic.com/kyverno/policy/node-placement: "poc-worker"
        smaitic.com/kyverno/resources/requests: "cpu=250m,memory=256Mi"
        smaitic.com/kyverno/resources/limits: "cpu=500m,memory=512Mi"
        smaitic.com/kyverno/health-config: "bridge"
        smaitic.com/launcher-script: "app-launcher"
    spec:
      containers:
        - name: full-injection
          image: busybox:1.37
          command: ["sleep", "3600"]
          ports:
            - containerPort: 9988
