apiVersion: apps/v1
kind: Deployment
metadata:
  name: probes-bridge
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probes-bridge
  template:
    metadata:
      labels:
        app: probes-bridge
      annotations:
        {{ .Values.annotationKey }}: "probes-bridge"
        smaitic.com/kyverno/health-config: "bridge"
    spec:
      containers:
        - name: app
          image: {{ .Values.app.image }}
          command: ["sleep", "3600"]
          ports:
            - containerPort: 9988
