apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-parser-cmd
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: init-parser-cmd
  template:
    metadata:
      labels:
        app: init-parser-cmd
      annotations:
        {{ .Values.annotationKey }}: "init-parser-cmd"
        smaitic.com/launcher-script: "init-parser"
    spec:
      containers:
        - name: app
          image: {{ .Values.app.image }}
          command: ["sleep", "3600"]
