apiVersion: apps/v1
kind: Deployment
metadata:
  name: probes-nginx
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probes-nginx
  template:
    metadata:
      labels:
        app: probes-nginx
      annotations:
        {{ .Values.annotationKey }}: "probes-nginx"
        smaitic.com/health-config: "nginx-static"
    spec:
      containers:
        - name: app
          image: {{ .Values.app.image }}
          command: ["sleep", "3600"]
          ports:
            - containerPort: 8080
