apiVersion: apps/v1
kind: Deployment
metadata:
  name: launcher-cmd
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: launcher-cmd
  template:
    metadata:
      labels:
        app: launcher-cmd
      annotations:
        {{ .Values.annotationKey }}: "launcher-cmd"
        smaitic.com/launcher-script: "app-launcher"
    spec:
      containers:
        - name: app
          image: {{ .Values.app.image }}
          command: ["sleep", "3600"]
