apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-health-probes
spec:
  background: false
  rules:

    - name: inject-probes-bridge
      match:
        any:
          - resources:
              kinds:
                - Pod
              annotations:
                smaitic.com/health-config: "bridge"
      preconditions:
        all:
          - key: '{{ "{{ request.object.metadata.annotations.\"smaitic.com/health-config\" }}" }}'
            operator: Equals
            value: "bridge"
      mutate:
        patchStrategicMerge:
          spec:
            containers:
              - (name): "*"
                livenessProbe:
                  httpGet:
                    path: "/actuator/health/liveness"
                    port: 9988
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  failureThreshold: 3
                  timeoutSeconds: 10
                readinessProbe:
                  httpGet:
                    path: "/actuator/health/readiness"
                    port: 9988
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  failureThreshold: 3
                  timeoutSeconds: 10

    - name: inject-probes-nginx-static
      match:
        any:
          - resources:
              kinds:
                - Pod
              annotations:
                smaitic.com/health-config: "nginx-static"
      preconditions:
        all:
          - key: '{{ "{{ request.object.metadata.annotations.\"smaitic.com/health-config\" }}" }}'
            operator: Equals
            value: "nginx-static"
      mutate:
        patchStrategicMerge:
          spec:
            containers:
              - (name): "*"
                livenessProbe:
                  httpGet:
                    path: "/"
                    port: 8080
                  initialDelaySeconds: 10
                  periodSeconds: 30
                  failureThreshold: 3
                  timeoutSeconds: 10
                readinessProbe:
                  httpGet:
                    path: "/"
                    port: 8080
                  initialDelaySeconds: 10
                  periodSeconds: 30
                  failureThreshold: 3
                  timeoutSeconds: 10

    - name: inject-probes-custom
      match:
        any:
          - resources:
              kinds:
                - Pod
              annotations:
                smaitic.com/health-config: "custom"
                smaitic.com/health-port: "?*"
                smaitic.com/health-path: "?*"
      preconditions:
        all:
          - key: '{{ "{{ request.object.metadata.annotations.\"smaitic.com/health-config\" }}" }}'
            operator: Equals
            value: "custom"
      mutate:
        patchStrategicMerge:
          spec:
            containers:
              - (name): "*"
                livenessProbe:
                  httpGet:
                    path: '{{ "{{ request.object.metadata.annotations.\"smaitic.com/health-path\" }}" }}'
                    port: '{{ "{{ to_number(request.object.metadata.annotations.\"smaitic.com/health-port\") }}" }}'
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  failureThreshold: 3
                  timeoutSeconds: 10
                readinessProbe:
                  httpGet:
                    path: '{{ "{{ request.object.metadata.annotations.\"smaitic.com/health-path\" }}" }}'
                    port: '{{ "{{ to_number(request.object.metadata.annotations.\"smaitic.com/health-port\") }}" }}'
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  failureThreshold: 3
                  timeoutSeconds: 10
