apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-resources
spec:
  background: false
  rules:

    - name: inject-resources-add
      match:
        any:
          - resources:
              kinds:
                - Pod
              annotations:
                smaitic.com/kyverno/resources/requests: "?*"
                smaitic.com/kyverno/resources/limits: "?*"
      preconditions:
        all:
          - key: "resources"
            operator: AnyNotIn
            value: '{{ "{{ request.object.spec.containers[0] | keys(@) }}" }}'
      mutate:
        patchStrategicMerge:
          spec:
            containers:
              - (name): "*"
                resources:
                  requests:
                    cpu: '{{ "{{ split(split(request.object.metadata.annotations.\"smaitic.com/kyverno/resources/requests\", \",\")[0], \"=\")[1] }}" }}'
                    memory: '{{ "{{ split(split(request.object.metadata.annotations.\"smaitic.com/kyverno/resources/requests\", \",\")[1], \"=\")[1] }}" }}'
                  limits:
                    cpu: '{{ "{{ split(split(request.object.metadata.annotations.\"smaitic.com/kyverno/resources/limits\", \",\")[0], \"=\")[1] }}" }}'
                    memory: '{{ "{{ split(split(request.object.metadata.annotations.\"smaitic.com/kyverno/resources/limits\", \",\")[1], \"=\")[1] }}" }}'

    - name: inject-resources-replace
      match:
        any:
          - resources:
              kinds:
                - Pod
              annotations:
                smaitic.com/kyverno/resources/requests: "?*"
                smaitic.com/kyverno/resources/limits: "?*"
      preconditions:
        all:
          - key: "resources"
            operator: AnyIn
            value: '{{ "{{ request.object.spec.containers[0] | keys(@) }}" }}'
      mutate:
        patchStrategicMerge:
          spec:
            containers:
              - (name): "*"
                resources:
                  requests:
                    cpu: '{{ "{{ split(split(request.object.metadata.annotations.\"smaitic.com/kyverno/resources/requests\", \",\")[0], \"=\")[1] }}" }}'
                    memory: '{{ "{{ split(split(request.object.metadata.annotations.\"smaitic.com/kyverno/resources/requests\", \",\")[1], \"=\")[1] }}" }}'
                  limits:
                    cpu: '{{ "{{ split(split(request.object.metadata.annotations.\"smaitic.com/kyverno/resources/limits\", \",\")[0], \"=\")[1] }}" }}'
                    memory: '{{ "{{ split(split(request.object.metadata.annotations.\"smaitic.com/kyverno/resources/limits\", \",\")[1], \"=\")[1] }}" }}'
