apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-node-placement
spec:
  background: false
  rules:
    - name: inject-node-placement
      match:
        any:
          - resources:
              kinds:
                - Pod
              annotations:
                smaitic.com/node-placement: "?*"
      mutate:
        patchStrategicMerge:
          spec:
            nodeSelector:
              demo.smaitic.com/role: '{{ "{{ request.object.metadata.annotations.\"smaitic.com/node-placement\" }}" }}'
            tolerations:
              - key: demo.smaitic.com/reserved-for
                value: '{{ "{{ request.object.metadata.annotations.\"smaitic.com/node-placement\" }}" }}'
                effect: NoSchedule
                operator: Equal
