apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-secrets-parser
  annotations:
    policies.kyverno.io/title: "Inject Secrets Parser Init Container"
    policies.kyverno.io/category: "Secrets Management"
    policies.kyverno.io/subject: "Pod, InitContainer"
spec:
  background: false
  rules:
    # Rule 1: pod has NO initContainers. inject secrets-parser (position 0)
    - name: inject-init-no-existing
      match:
        any:
          - resources:
              kinds:
                - Pod
              annotations:
                smaitic.com/inject-secrets-poc: "?*"
      preconditions:
        all:
          - key: "initContainers"
            operator: AnyNotIn
            value: "{{ request.object.spec | keys(@) }}"
      mutate:
        patchStrategicMerge:
          spec:
            initContainers:
              - name: secrets-parser
                image: "busybox:latest"
                command:
                  - "/bin/sh"
                  - "-c"
                  - "echo '[POC] secrets-parser dummy init done' && sleep 2"
                volumeMounts:
                  - name: secrets-store-inline
                    mountPath: "/mnt/raw-secrets"
                    readOnly: true
                  - name: shared-memory
                    mountPath: "/mnt/shared"
                  - name: init-scripts
                    mountPath: "/scripts"

    # Rule 2: Pod HAS initContainers — insert secrets-parser at position 0
    - name: inject-init-with-existing
      match:
        any:
          - resources:
              kinds:
                - Pod
              annotations:
                smaitic.com/inject-secrets-poc: "?*"
      preconditions:
        all:
          - key: "initContainers"
            operator: AnyIn
            value: "{{ request.object.spec | keys(@) }}"
          - key: "{{ request.object.spec.initContainers[0].name }}"
            operator: NotEquals
            value: "secrets-parser"
      mutate:
        patchesJson6902: |-
          - op: add
            path: /spec/initContainers/0
            value:
              name: secrets-parser
              image: "busybox:latest"
              command:
                - "/bin/sh"
                - "-c"
                - "echo '[POC] secrets-parser dummy init done' && sleep 2"
              volumeMounts:
                - name: secrets-store-inline
                  mountPath: "/mnt/raw-secrets"
                  readOnly: true
                - name: shared-memory
                  mountPath: "/mnt/shared"
                - name: init-scripts
                  mountPath: "/scripts"
