apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-command-prefix
  annotations:
    policies.kyverno.io/title: "Inject App Launcher Command Prefix"
    policies.kyverno.io/category: "Workload Management"
    policies.kyverno.io/subject: "Pod, Container"
spec:
  background: false
  rules:
    - name: inject-command-prefix
      match:
        any:
          - resources:
              kinds:
                - Pod
              annotations:
                smaitic.com/inject-secrets-poc: "?*"
      preconditions:
        all:
          - key: "command"
            operator: AnyIn
            value: "{{ request.object.spec.containers[0] | keys(@) }}"
          - key: "{{ request.object.spec.containers[0].command[0] }}"
            operator: NotEquals
            value: "/scripts/app_launcher.sh"
      mutate:
        patchesJson6902: |-
          - op: add
            path: /spec/containers/0/command/0
            value: "/scripts/app_launcher.sh"
