apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-secrets-parser
  annotations:
    policies.kyverno.io/title: "Inject Secrets Parser and Volumes"
    policies.kyverno.io/category: "Secrets Management"
    policies.kyverno.io/subject: "Pod, InitContainer, Volume"
spec:
  background: false
  rules:
    - name: inject-init-and-volumes
      match:
        any:
          - resources:
              kinds:
                - Pod
              annotations:
                smaitic.com/inject-secrets-poc: "?*"
      mutate:
        patchStrategicMerge:
          spec:
            initContainers:
              - name: secrets-parser
                image: "busybox:latest"
                command:
                  - "/bin/sh"
                  - "-c"
                  - "echo '[POC] secrets-parser dummy init done' && sleep 2"
                volumeMounts:
                  - name: secrets-store-inline
                    mountPath: "/mnt/raw-secrets"
                    readOnly: true
                  - name: shared-memory
                    mountPath: "/mnt/shared"
                  - name: init-scripts
                    mountPath: "/scripts"
            volumes:
              - name: secrets-store-inline
                emptyDir: {}
              - name: shared-memory
                emptyDir:
                  medium: Memory
                  sizeLimit: 10Mi
              - name: init-scripts
                emptyDir: {}
